# Site settings
title: Mike Patel
name: Mike Patel

# Build settings
markdown: kramdown

#Intro
introduction: |
   <strong>About Me</strong>: Highly motivated, DevOps trained full stack engineer with a passion for building great products and pushing boundaries. I have a wealth of experience developing software on the JVM platform, primarily in Java and Scala. I am comfortable in client facing conversations, and have experience working in a solutions engineering role. I also have spent several years as a Technical Lead and, as such, am familiar with mentoring and technical management. 
   <br/></br><strong>Industry Expertise</strong>: I have a detailed understanding of the online marketing industry, with advanced knowledge of user tracking and segmentation technology. I am also familiar with insurance products, having spent a few years working with them during my tenure at Accenture.
   <br/></br><strong>Development Ideology</strong>: I thrive most in agile environments, with a strong focus on iterative product development through client collaboration.
   <ul>
   <li>I am in favour of lean solutions</li>
   <li>Good agile teams should be self-organizing</li>
   <li>I think specification by example is a worthwhile investment</li>
   <li>I prefer workflows that involve pre-merge code review</li>
   <li>Continuous Integration is a must.</li>
   <li>I like frameworks, but am cautious of how they influence your application design</li>
   <li>I believe developers should take responsibility for how their software runs in production.</li>
   </ul>


#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://nerd-ability.blogspot.co.uk/
 - title: GitHub
   url: https://github.com/patelm5
 - title: StackOverflow
   url: http://stackoverflow.com/users/441478/mikepatel
 - title: LinkedIn
   url: https://uk.linkedin.com/in/michael-patel-58855535

#Any buzzword skills you want to include


skills:
   core: 
    - Java 8 
    - Scala
    - Spring 4
    - Akka
    - Akka Streams
    - JPA
    - Hazelcast
    - RabbitMQ
    - SQL
   scripting: 
    - Bash
    - Ant
    - Groovy
    - Ruby
   frontend:
    - JavaScript
    - HTML
    - CSS
    - React
    - JSP
    - Thymeleaf
    - Angular
    - Google Closure
    - TypeScript
   build: 
    - Maven
    - Gradle	
    - SBT
    - Webpack
    - Gulp
   version-control: 
    - Git
    - SVN
   deployment: 
    - Jenkins
    - Chef
    - Puppet
    - Docker
    - Tomcat
    - Apache2
    - Mesos
    - Marathon
    - Consul
    - Zookeeper
   monitoring:
    - Graylog 2
    - Graphite
    - Nagios
    - Check MK
    - Monitis
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed:
  - url: http://nerd-ability.blogspot.com/feeds/posts/default
    author: Michael Patel
  - url: http://techblog.betgenius.com/rss/
    author: Mike Patel
#Work experience is required
roles:
 - title: Connextra Technical Lead
   start: 2013
   end: Ongoing
   employer: Betgenius
   description: Connextra is an advertising platform that specializes in producing rich dynamic creative based on live sports data.
 - title: Software Engineer
   start: 2011
   end: 2013
   employer: Betgenius
   description: Working primarily on real-time, whitelabeled, sports widgets for visualizing the state of games, when TV rights are unavailable.
 - title: Senior Programmer
   start: 2010
   end: 2011
   employer: Accenture
   description: Range of technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level: Master of Science (M.Sc.)
   grade: Distinction
   date: 2009
   subject: Advanced Computer Science
   school: University of Manchester
 - level: Bachelor of Science (B.Sc.)
   grade: 2:1
   date: 2008
   subject: Computer Science
   school: University of Manchester

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: June 3, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/algo
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: September 3, 2013
    - title: Principles of Reactive Programming
      link: https://www.coursera.org/course/reactive
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: January 21, 2014

#List of interesting Github repo/projects to include - optional
github:
 - patelm5/patelm5.github.io
 - patelm5/jmeter-maven-plugin
 - patelm5/atmosphere-rabbitmq-example
 - patelm5/spring-social-thymeleaf-example
 - betgenius/krasa-jaxb-tools
 - betgenius/plovr-maven-plugin
 - patelm5/performance-plugin

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/441478/mikepatel
   flairimageurl: http://stackoverflow.com/users/flair/441478.png


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
